// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceSpreadsheetEmulator.Persistence.Database;

#nullable disable

namespace SpaceSpreadsheetEmulator.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("account_ids", "identity")
                .IncrementsBy(10);

            modelBuilder.HasSequence("character_ids", "characters")
                .StartsAt(90000001L)
                .IncrementsBy(10);

            modelBuilder.HasSequence("item_ids", "inventory")
                .StartsAt(190000001L)
                .IncrementsBy(10);

            modelBuilder.Entity("SpaceSpreadsheetEmulator.Persistence.Entities.AccountEntity", b =>
                {
                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("AccountId"), "account_ids", "identity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_user_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("AccountId");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_accounts_normalized_user_name");

                    b.ToTable("accounts", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_accounts_account_id_positive", "account_id > 0");

                            t.HasCheckConstraint("ck_accounts_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("SpaceSpreadsheetEmulator.Persistence.Entities.CharacterEntity", b =>
                {
                    b.Property<long>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("CharacterId"), "character_ids", "characters");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("ActiveShipItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("active_ship_item_id");

                    b.Property<int>("AncestryId")
                        .HasColumnType("integer")
                        .HasColumnName("ancestry_id");

                    b.Property<int>("BloodlineId")
                        .HasColumnType("integer")
                        .HasColumnName("bloodline_id");

                    b.Property<int>("CharacterTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("character_type_id");

                    b.Property<int>("ConstellationId")
                        .HasColumnType("integer")
                        .HasColumnName("constellation_id");

                    b.Property<int>("CorporationId")
                        .HasColumnType("integer")
                        .HasColumnName("corporation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer")
                        .HasColumnName("race_id");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.Property<int>("SolarSystemId")
                        .HasColumnType("integer")
                        .HasColumnName("solar_system_id");

                    b.Property<int?>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("CharacterId");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_characters_account_id");

                    b.HasIndex("ActiveShipItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_characters_active_ship_item_id");

                    b.ToTable("characters", "characters", t =>
                        {
                            t.HasCheckConstraint("ck_characters_account_id_positive", "account_id > 0");

                            t.HasCheckConstraint("ck_characters_active_ship_positive", "active_ship_item_id > 0");

                            t.HasCheckConstraint("ck_characters_character_id_positive", "character_id > 0");

                            t.HasCheckConstraint("ck_characters_location_ids_positive", "(station_id IS NULL OR station_id > 0) AND solar_system_id > 0 AND constellation_id > 0 AND region_id > 0");

                            t.HasCheckConstraint("ck_characters_static_ids_positive", "race_id > 0 AND bloodline_id > 0 AND ancestry_id > 0 AND character_type_id > 0 AND corporation_id > 0");

                            t.HasCheckConstraint("ck_characters_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("SpaceSpreadsheetEmulator.Persistence.Entities.CharacterLocationTransitionEntity", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<long>("CharacterId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<long>("ResultingCharacterVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("resulting_character_version");

                    b.Property<long>("ResultingShipVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("resulting_ship_version");

                    b.Property<long>("ShipId")
                        .HasColumnType("bigint")
                        .HasColumnName("ship_id");

                    b.Property<int>("SolarSystemId")
                        .HasColumnType("integer")
                        .HasColumnName("solar_system_id");

                    b.Property<int?>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.HasKey("IdempotencyKey");

                    b.HasIndex("CharacterId", "ResultingCharacterVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_character_location_transitions_character_version");

                    b.ToTable("character_location_transitions", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_character_location_transitions_kind", "kind IN (1, 2)");

                            t.HasCheckConstraint("ck_character_location_transitions_positive_ids", "account_id > 0 AND character_id > 0 AND ship_id > 0 AND solar_system_id > 0");

                            t.HasCheckConstraint("ck_character_location_transitions_station", "station_id IS NULL OR station_id > 0");

                            t.HasCheckConstraint("ck_character_location_transitions_versions", "resulting_character_version > 0 AND resulting_ship_version > 0");
                        });
                });

            modelBuilder.Entity("SpaceSpreadsheetEmulator.Persistence.Entities.InventoryItemEntity", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseHiLo(b.Property<long>("ItemId"), "item_ids", "inventory");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("custom_name");

                    b.Property<short>("Flag")
                        .HasColumnType("smallint")
                        .HasColumnName("flag");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint")
                        .HasColumnName("location_id");

                    b.Property<short>("LocationKind")
                        .HasColumnType("smallint")
                        .HasColumnName("location_kind");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint")
                        .HasColumnName("quantity");

                    b.Property<bool>("Singleton")
                        .HasColumnType("boolean")
                        .HasColumnName("singleton");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("ItemId");

                    b.HasIndex("LocationKind", "LocationId", "Flag")
                        .HasDatabaseName("ix_items_location_flag");

                    b.HasIndex("OwnerId", "LocationKind", "LocationId")
                        .HasDatabaseName("ix_items_owner_location");

                    b.ToTable("items", "inventory", t =>
                        {
                            t.HasCheckConstraint("ck_items_flag", "flag IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("ck_items_location_kind", "location_kind IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("ck_items_positive_ids", "item_id > 0 AND type_id > 0 AND owner_id > 0 AND location_id > 0");

                            t.HasCheckConstraint("ck_items_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_items_singleton_quantity", "NOT singleton OR quantity = 1");

                            t.HasCheckConstraint("ck_items_updated_after_created", "updated_at >= created_at");

                            t.HasCheckConstraint("ck_items_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("SpaceSpreadsheetEmulator.Persistence.Entities.SolarSystemSnapshotEntity", b =>
                {
                    b.Property<int>("SolarSystemId")
                        .HasColumnType("integer")
                        .HasColumnName("solar_system_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("integer")
                        .HasColumnName("format_version");

                    b.Property<long>("LastSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_sequence");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload");

                    b.Property<byte[]>("PayloadSha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload_sha256");

                    b.Property<long>("SourceEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("source_epoch");

                    b.Property<long>("Tick")
                        .HasColumnType("bigint")
                        .HasColumnName("tick");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("SolarSystemId");

                    b.ToTable("solar_system_snapshots", "simulation", t =>
                        {
                            t.HasCheckConstraint("ck_solar_system_snapshots_format_version", "format_version > 0");

                            t.HasCheckConstraint("ck_solar_system_snapshots_hash_length", "octet_length(payload_sha256) = 32");

                            t.HasCheckConstraint("ck_solar_system_snapshots_last_sequence", "last_sequence >= 0");

                            t.HasCheckConstraint("ck_solar_system_snapshots_source_epoch", "source_epoch > 0");

                            t.HasCheckConstraint("ck_solar_system_snapshots_system_id", "solar_system_id > 0");

                            t.HasCheckConstraint("ck_solar_system_snapshots_tick", "tick >= 0");

                            t.HasCheckConstraint("ck_solar_system_snapshots_version", "version > 0");
                        });
                });

            modelBuilder.Entity("SpaceSpreadsheetEmulator.Persistence.Entities.CharacterEntity", b =>
                {
                    b.HasOne("SpaceSpreadsheetEmulator.Persistence.Entities.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpaceSpreadsheetEmulator.Persistence.Entities.InventoryItemEntity", null)
                        .WithMany()
                        .HasForeignKey("ActiveShipItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
